POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "uriel@equipo1.com",
    "password": "159357"
}

###
GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzOTQxNzM4LCJleHAiOjE3MzM5NDIwMzh9.eQBs4yExFKtjH3yhZka2UsLv_OCBOwpYLlk8E4r-ID8