GET http://localhost:3000/pokemons

###
GET http://localhost:3000/pokemons/play

###
//Obtener por id
GET http://localhost:3000/pokemons/25

###
//Crear
POST http://localhost:3000/pokemons
Content-Type: application/json

{
    "name": "Uriel",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6.svg"
}

###
//Editar
PUT http://localhost:3000/pokemons/1
Content-Type: application/json

{
    "name": "mega-charizard",
    "image": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6-mega.svg"
}

###
//Eliminar
DELETE http://localhost:3000/pokemons/154